# Generated by Django 3.2.3 on 2021-06-16 14:22

from django.db import migrations, models
import gestorpersonas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gestorpersonas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=50, validators=[gestorpersonas.validators.validar_rut]),
        ),
    ]
