# Generated by Django 3.2.3 on 2021-06-18 14:09

from django.db import migrations, models
import django.db.models.deletion
import gestorpersonas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gestorpersonas', '0002_alter_persona_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefonoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, validators=[gestorpersonas.validators.validar_telefono_chileno])),
                ('descripcion', models.CharField(max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorpersonas.persona')),
            ],
        ),
    ]
